export { css };

const css = {
    wrapper: 'sw-table',
    table: 'sw-table-table',
    theadTr: 'sw-table-thead-tr',
    tbody: 'sw-table-tbody',
    th: 'sw-table-th',
    tr: 'sw-table-tr',
    trEven: 'sw-table-tr-even',
    trOdd: 'sw-table-tr-odd',
    td: 'sw-table-td',
    detailTr: 'sw-table-detail-tr',
    checkbox: 'sw-table-checkbox',
    dropdownButton: 'sw-table-dropdown-button',
    detailButton: 'sw-table-detail-button',
    actionsButton: 'sw-table-actions-button',
    detailIsOpen: 'sw-table-detail-tr-open',
    tfoot: 'sw-table-tfoot',
    searchInputWrapper: 'sw-table-search-wrapper',
    searchInput: 'sw-table-search',
    icon: 'sw-table-icon',
    searchIgnore: 'sw-table-search-ignore',
    header: 'sw-table-header',
} as const;